In [1]:
import csv
import numpy as np 
import matplotlib.pyplot as plt
from tqdm import tqdm
import pandas as pd
import pickle as pkl
import random

import os

In [2]:


# First attempt it with one file
file1 = "./data/hw_dataset/parkinson/P_02100002.txt"
control = "./data/hw_dataset/control/C_000"
file2 = "./data/new_dataset/parkinson"
new_data = "G:/My Drive/Sys Lab/modified_data"
x0, y0 = 200.0, 204.0
xmin, xmax = 32.0, 401.25

parkinsons_1= "./data/hw_dataset/parkinson/"

In [7]:
def get_subset(X, y, filename):
    subset = [] # format ([Xi, X2. . . Xf], [yi, y2, . . . yf])
    X_temp, y_temp = [], []
    for i in tqdm(range(len(X)-50)): # was len(X)
        # X_temp.append(X[i])
        # y_temp.append(y[i])
        if i<=50:
            continue
        combined_array = np.column_stack((X[i:i+50], y[i:i+50]))
        angle = random.randint(1, 360)
        theta = np.radians(angle)  # Convert the angle to radians
        rotation_matrix = np.array([[np.cos(theta), -np.sin(theta)], 
                                    [np.sin(theta), np.cos(theta)]])
        rotated = np.dot(combined_array, rotation_matrix)
        shape = 50
        print(rotated[:-1])
        print()
        print(rotated[-1])
        print()
        input()
        subset.append((filename, i, angle, rotated[:-1], rotated[-1], shape))
    print(subset)

    return subset

In [8]:

def read_data(filename, label="name"): 
    with open(filename) as source:
        reader = csv.reader(source, delimiter=';')
        x = []
        # X ; Y; Z; Pressure; GripAngle; Timestamp; Test ID
        # 9 second intervals --> 
        # 0: Static Spiral Test ( Draw on the given spiral pattern)
        # 1: Dynamic Spiral Test ( Spiral pattern will blink in a certain time, so subjects need to continue on their draw)
        # 2: Circular Motion Test (Subjectd draw circles around the red point)
        for line in reader:
            x.append(line)
        df = np.array(x)
        df = df.astype(float)
        cond1 = (np.array([df[:, 2]])).T
        
        # Split based on Test 
        cond = (np.array([df[:, -1]])).T
        df_stat = df[cond[:,0]==0]
        df_dyn = df[cond[:,0]==1]
        df_circ = df[cond[:,0]==2]

        
        X, y, z, c, t = df_stat[:,0], df_stat[:,1], df_stat[:,2], df_stat[:, 3], df_stat[:, 4]
        print(t.size)
        
        X = X * (xmax-xmin)/(X.max()-X.min())
        X = X- (X[0]-x0)
        y = y- (y[0]-y0)
        c = (c-c.min())/(c.max()-c.min())
        c= c.astype(str)
        
        
        #plt.scatter(X, y, c=c, cmap='viridis')
        get_subset(X, y, filename)


In [9]:
def visualize_subsets(filepath):
    with open(filepath, 'rb') as f:
        classification_dict = pkl.load(f)
        print(classification_dict)


In [10]:

#visualize_subsets(f"{new_data}/dummy.pkl")

parkinsons_1 = "./data/new_dataset/parkinson/"
ls = os.listdir(parkinsons_1)
for i in ls[0:1]:
    file1 = f"data/new_dataset/parkinson/{i}"
    read_data(f"./{file1}", label="Parkinson's")

# for i in range(1,10):
#     control = "data/hw_dataset/control/C_000"
#     read_data(f"./{control}{i}.txt", label=f"control{i}")

# print(xmin/8, xmax/8)

# plt.legend(loc="upper left")
# plt.show()

4616


  0%|          | 0/4566 [00:00<?, ?it/s]

[[ 20.15185342 287.12872166]
 [ 20.15185342 287.12872166]
 [ 20.15185342 287.12872166]
 [ 20.15185342 287.12872166]
 [ 20.15185342 287.12872166]
 [ 20.15185342 287.12872166]
 [ 20.15185342 287.12872166]
 [ 20.15185342 287.12872166]
 [ 20.15185342 287.12872166]
 [ 20.15185342 287.12872166]
 [ 20.15185342 287.12872166]
 [ 20.15185342 287.12872166]
 [ 20.15185342 287.12872166]
 [ 20.15185342 287.12872166]
 [ 20.15185342 287.12872166]
 [ 20.15185342 287.12872166]
 [ 20.15185342 287.12872166]
 [ 20.15185342 287.12872166]
 [ 20.15185342 287.12872166]
 [ 20.15185342 287.12872166]
 [ 20.15185342 287.12872166]
 [ 20.15185342 287.12872166]
 [ 20.15185342 287.12872166]
 [ 19.50906581 287.89476611]
 [ 18.74250237 287.251543  ]
 [ 18.74250237 287.251543  ]
 [ 18.74250237 287.251543  ]
 [ 18.74250237 287.251543  ]
 [ 18.74250237 287.251543  ]
 [ 18.74250237 287.251543  ]
 [ 18.74250237 287.251543  ]
 [ 20.15185342 287.12872166]
 [ 20.15185342 287.12872166]
 [ 20.15185342 287.12872166]
 [ 20.15185342

  1%|          | 52/4566 [00:08<12:56,  5.81it/s]

[[ -20.15185342 -287.12872166]
 [ -20.15185342 -287.12872166]
 [ -20.15185342 -287.12872166]
 [ -20.15185342 -287.12872166]
 [ -20.15185342 -287.12872166]
 [ -20.15185342 -287.12872166]
 [ -20.15185342 -287.12872166]
 [ -20.15185342 -287.12872166]
 [ -20.15185342 -287.12872166]
 [ -20.15185342 -287.12872166]
 [ -20.15185342 -287.12872166]
 [ -20.15185342 -287.12872166]
 [ -20.15185342 -287.12872166]
 [ -20.15185342 -287.12872166]
 [ -20.15185342 -287.12872166]
 [ -20.15185342 -287.12872166]
 [ -20.15185342 -287.12872166]
 [ -20.15185342 -287.12872166]
 [ -20.15185342 -287.12872166]
 [ -20.15185342 -287.12872166]
 [ -20.15185342 -287.12872166]
 [ -20.15185342 -287.12872166]
 [ -19.50906581 -287.89476611]
 [ -18.74250237 -287.251543  ]
 [ -18.74250237 -287.251543  ]
 [ -18.74250237 -287.251543  ]
 [ -18.74250237 -287.251543  ]
 [ -18.74250237 -287.251543  ]
 [ -18.74250237 -287.251543  ]
 [ -18.74250237 -287.251543  ]
 [ -20.15185342 -287.12872166]
 [ -20.15185342 -287.12872166]
 [ -20.1

  1%|          | 53/4566 [00:10<15:47,  4.76it/s]

[[121.71110715 260.83597604]
 [121.71110715 260.83597604]
 [121.71110715 260.83597604]
 [121.71110715 260.83597604]
 [121.71110715 260.83597604]
 [121.71110715 260.83597604]
 [121.71110715 260.83597604]
 [121.71110715 260.83597604]
 [121.71110715 260.83597604]
 [121.71110715 260.83597604]
 [121.71110715 260.83597604]
 [121.71110715 260.83597604]
 [121.71110715 260.83597604]
 [121.71110715 260.83597604]
 [121.71110715 260.83597604]
 [121.71110715 260.83597604]
 [121.71110715 260.83597604]
 [121.71110715 260.83597604]
 [121.71110715 260.83597604]
 [121.71110715 260.83597604]
 [121.71110715 260.83597604]
 [121.38553899 261.78149462]
 [120.43937982 261.45570589]
 [120.43937982 261.45570589]
 [120.43937982 261.45570589]
 [120.43937982 261.45570589]
 [120.43937982 261.45570589]
 [120.43937982 261.45570589]
 [120.43937982 261.45570589]
 [121.71110715 260.83597604]
 [121.71110715 260.83597604]
 [121.71110715 260.83597604]
 [121.71110715 260.83597604]
 [121.71110715 260.83597604]
 [121.71110715

  1%|          | 54/4566 [00:25<57:21,  1.31it/s]

[[ -40.13185165 -285.02356829]
 [ -40.13185165 -285.02356829]
 [ -40.13185165 -285.02356829]
 [ -40.13185165 -285.02356829]
 [ -40.13185165 -285.02356829]
 [ -40.13185165 -285.02356829]
 [ -40.13185165 -285.02356829]
 [ -40.13185165 -285.02356829]
 [ -40.13185165 -285.02356829]
 [ -40.13185165 -285.02356829]
 [ -40.13185165 -285.02356829]
 [ -40.13185165 -285.02356829]
 [ -40.13185165 -285.02356829]
 [ -40.13185165 -285.02356829]
 [ -40.13185165 -285.02356829]
 [ -40.13185165 -285.02356829]
 [ -40.13185165 -285.02356829]
 [ -40.13185165 -285.02356829]
 [ -40.13185165 -285.02356829]
 [ -40.13185165 -285.02356829]
 [ -39.5440664  -285.83258529]
 [ -38.73450129 -285.24440181]
 [ -38.73450129 -285.24440181]
 [ -38.73450129 -285.24440181]
 [ -38.73450129 -285.24440181]
 [ -38.73450129 -285.24440181]
 [ -38.73450129 -285.24440181]
 [ -38.73450129 -285.24440181]
 [ -40.13185165 -285.02356829]
 [ -40.13185165 -285.02356829]
 [ -40.13185165 -285.02356829]
 [ -40.13185165 -285.02356829]
 [ -40.1

  1%|          | 55/4566 [00:25<55:06,  1.36it/s]

[[-238.58484041  161.01637783]
 [-238.58484041  161.01637783]
 [-238.58484041  161.01637783]
 [-238.58484041  161.01637783]
 [-238.58484041  161.01637783]
 [-238.58484041  161.01637783]
 [-238.58484041  161.01637783]
 [-238.58484041  161.01637783]
 [-238.58484041  161.01637783]
 [-238.58484041  161.01637783]
 [-238.58484041  161.01637783]
 [-238.58484041  161.01637783]
 [-238.58484041  161.01637783]
 [-238.58484041  161.01637783]
 [-238.58484041  161.01637783]
 [-238.58484041  161.01637783]
 [-238.58484041  161.01637783]
 [-238.58484041  161.01637783]
 [-238.58484041  161.01637783]
 [-239.56964816  160.84272965]
 [-239.39588233  159.85725468]
 [-239.39588233  159.85725468]
 [-239.39588233  159.85725468]
 [-239.39588233  159.85725468]
 [-239.39588233  159.85725468]
 [-239.39588233  159.85725468]
 [-239.39588233  159.85725468]
 [-238.58484041  161.01637783]
 [-238.58484041  161.01637783]
 [-238.58484041  161.01637783]
 [-238.58484041  161.01637783]
 [-238.58484041  161.01637783]
 [-238.5

  1%|          | 56/4566 [00:26<52:14,  1.44it/s]

[[-177.15087004  226.86244565]
 [-177.15087004  226.86244565]
 [-177.15087004  226.86244565]
 [-177.15087004  226.86244565]
 [-177.15087004  226.86244565]
 [-177.15087004  226.86244565]
 [-177.15087004  226.86244565]
 [-177.15087004  226.86244565]
 [-177.15087004  226.86244565]
 [-177.15087004  226.86244565]
 [-177.15087004  226.86244565]
 [-177.15087004  226.86244565]
 [-177.15087004  226.86244565]
 [-177.15087004  226.86244565]
 [-177.15087004  226.86244565]
 [-177.15087004  226.86244565]
 [-177.15087004  226.86244565]
 [-177.15087004  226.86244565]
 [-178.14113811  227.00161875]
 [-178.2804055   226.01067977]
 [-178.2804055   226.01067977]
 [-178.2804055   226.01067977]
 [-178.2804055   226.01067977]
 [-178.2804055   226.01067977]
 [-178.2804055   226.01067977]
 [-178.2804055   226.01067977]
 [-177.15087004  226.86244565]
 [-177.15087004  226.86244565]
 [-177.15087004  226.86244565]
 [-177.15087004  226.86244565]
 [-177.15087004  226.86244565]
 [-177.15087004  226.86244565]
 [-177.1

  1%|          | 57/4566 [00:26<48:39,  1.54it/s]

[[-270.50163665  -98.37613823]
 [-270.50163665  -98.37613823]
 [-270.50163665  -98.37613823]
 [-270.50163665  -98.37613823]
 [-270.50163665  -98.37613823]
 [-270.50163665  -98.37613823]
 [-270.50163665  -98.37613823]
 [-270.50163665  -98.37613823]
 [-270.50163665  -98.37613823]
 [-270.50163665  -98.37613823]
 [-270.50163665  -98.37613823]
 [-270.50163665  -98.37613823]
 [-270.50163665  -98.37613823]
 [-270.50163665  -98.37613823]
 [-270.50163665  -98.37613823]
 [-270.50163665  -98.37613823]
 [-270.50163665  -98.37613823]
 [-270.94000779  -99.27493227]
 [-270.04060481  -99.71360042]
 [-270.04060481  -99.71360042]
 [-270.04060481  -99.71360042]
 [-270.04060481  -99.71360042]
 [-270.04060481  -99.71360042]
 [-270.04060481  -99.71360042]
 [-270.04060481  -99.71360042]
 [-270.50163665  -98.37613823]
 [-270.50163665  -98.37613823]
 [-270.50163665  -98.37613823]
 [-270.50163665  -98.37613823]
 [-270.50163665  -98.37613823]
 [-270.50163665  -98.37613823]
 [-270.50163665  -98.37613823]
 [-270.5

  1%|▏         | 58/4566 [00:26<44:44,  1.68it/s]

[[-287.13900061  -20.0048576 ]
 [-287.13900061  -20.0048576 ]
 [-287.13900061  -20.0048576 ]
 [-287.13900061  -20.0048576 ]
 [-287.13900061  -20.0048576 ]
 [-287.13900061  -20.0048576 ]
 [-287.13900061  -20.0048576 ]
 [-287.13900061  -20.0048576 ]
 [-287.13900061  -20.0048576 ]
 [-287.13900061  -20.0048576 ]
 [-287.13900061  -20.0048576 ]
 [-287.13900061  -20.0048576 ]
 [-287.13900061  -20.0048576 ]
 [-287.13900061  -20.0048576 ]
 [-287.13900061  -20.0048576 ]
 [-287.13900061  -20.0048576 ]
 [-287.80813122  -20.74800243]
 [-287.06448291  -21.41758637]
 [-287.06448291  -21.41758637]
 [-287.06448291  -21.41758637]
 [-287.06448291  -21.41758637]
 [-287.06448291  -21.41758637]
 [-287.06448291  -21.41758637]
 [-287.06448291  -21.41758637]
 [-287.13900061  -20.0048576 ]
 [-287.13900061  -20.0048576 ]
 [-287.13900061  -20.0048576 ]
 [-287.13900061  -20.0048576 ]
 [-287.13900061  -20.0048576 ]
 [-287.13900061  -20.0048576 ]
 [-287.13900061  -20.0048576 ]
 [-287.13900061  -20.0048576 ]
 [-287.1

  1%|▏         | 59/4566 [00:26<40:16,  1.87it/s]

[[-238.66724015 -160.89421519]
 [-238.66724015 -160.89421519]
 [-238.66724015 -160.89421519]
 [-238.66724015 -160.89421519]
 [-238.66724015 -160.89421519]
 [-238.66724015 -160.89421519]
 [-238.66724015 -160.89421519]
 [-238.66724015 -160.89421519]
 [-238.66724015 -160.89421519]
 [-238.66724015 -160.89421519]
 [-238.66724015 -160.89421519]
 [-238.66724015 -160.89421519]
 [-238.66724015 -160.89421519]
 [-238.66724015 -160.89421519]
 [-238.66724015 -160.89421519]
 [-238.87515184 -161.87236279]
 [-237.89634153 -162.08041534]
 [-237.89634153 -162.08041534]
 [-237.89634153 -162.08041534]
 [-237.89634153 -162.08041534]
 [-237.89634153 -162.08041534]
 [-237.89634153 -162.08041534]
 [-237.89634153 -162.08041534]
 [-238.66724015 -160.89421519]
 [-238.66724015 -160.89421519]
 [-238.66724015 -160.89421519]
 [-238.66724015 -160.89421519]
 [-238.66724015 -160.89421519]
 [-238.66724015 -160.89421519]
 [-238.66724015 -160.89421519]
 [-238.66724015 -160.89421519]
 [-238.66724015 -160.89421519]
 [-238.6

  1%|▏         | 60/4566 [00:26<36:01,  2.08it/s]

[[ 10.11892958 287.65710015]
 [ 10.11892958 287.65710015]
 [ 10.11892958 287.65710015]
 [ 10.11892958 287.65710015]
 [ 10.11892958 287.65710015]
 [ 10.11892958 287.65710015]
 [ 10.11892958 287.65710015]
 [ 10.11892958 287.65710015]
 [ 10.11892958 287.65710015]
 [ 10.11892958 287.65710015]
 [ 10.11892958 287.65710015]
 [ 10.11892958 287.65710015]
 [ 10.11892958 287.65710015]
 [ 10.11892958 287.65710015]
 [  9.44979897 288.40024497]
 [  8.70615066 287.73066102]
 [  8.70615066 287.73066102]
 [  8.70615066 287.73066102]
 [  8.70615066 287.73066102]
 [  8.70615066 287.73066102]
 [  8.70615066 287.73066102]
 [  8.70615066 287.73066102]
 [ 10.11892958 287.65710015]
 [ 10.11892958 287.65710015]
 [ 10.11892958 287.65710015]
 [ 10.11892958 287.65710015]
 [ 10.11892958 287.65710015]
 [ 10.11892958 287.65710015]
 [ 10.11892958 287.65710015]
 [ 10.11892958 287.65710015]
 [ 10.11892958 287.65710015]
 [ 10.11892958 287.65710015]
 [ 10.11892958 287.65710015]
 [ 10.11892958 287.65710015]
 [ 10.11892958

  1%|▏         | 61/4566 [00:44<4:36:27,  3.68s/it]

[[282.56073118  54.8491859 ]
 [282.56073118  54.8491859 ]
 [282.56073118  54.8491859 ]
 [282.56073118  54.8491859 ]
 [282.56073118  54.8491859 ]
 [282.56073118  54.8491859 ]
 [282.56073118  54.8491859 ]
 [282.56073118  54.8491859 ]
 [282.56073118  54.8491859 ]
 [282.56073118  54.8491859 ]
 [282.56073118  54.8491859 ]
 [282.56073118  54.8491859 ]
 [282.56073118  54.8491859 ]
 [283.13430762  55.66833794]
 [282.31460059  56.24230298]
 [282.31460059  56.24230298]
 [282.31460059  56.24230298]
 [282.31460059  56.24230298]
 [282.31460059  56.24230298]
 [282.31460059  56.24230298]
 [282.31460059  56.24230298]
 [282.56073118  54.8491859 ]
 [282.56073118  54.8491859 ]
 [282.56073118  54.8491859 ]
 [282.56073118  54.8491859 ]
 [282.56073118  54.8491859 ]
 [282.56073118  54.8491859 ]
 [282.56073118  54.8491859 ]
 [282.56073118  54.8491859 ]
 [282.56073118  54.8491859 ]
 [282.56073118  54.8491859 ]
 [282.56073118  54.8491859 ]
 [282.56073118  54.8491859 ]
 [282.56073118  54.8491859 ]
 [282.56073118

  1%|▏         | 62/4566 [00:44<3:40:33,  2.94s/it]

[[ 173.1645935  -229.91960238]
 [ 173.1645935  -229.91960238]
 [ 173.1645935  -229.91960238]
 [ 173.1645935  -229.91960238]
 [ 173.1645935  -229.91960238]
 [ 173.1645935  -229.91960238]
 [ 173.1645935  -229.91960238]
 [ 173.1645935  -229.91960238]
 [ 173.1645935  -229.91960238]
 [ 173.1645935  -229.91960238]
 [ 173.1645935  -229.91960238]
 [ 173.1645935  -229.91960238]
 [ 174.15228184 -230.07603685]
 [ 174.30882229 -229.08767934]
 [ 174.30882229 -229.08767934]
 [ 174.30882229 -229.08767934]
 [ 174.30882229 -229.08767934]
 [ 174.30882229 -229.08767934]
 [ 174.30882229 -229.08767934]
 [ 174.30882229 -229.08767934]
 [ 173.1645935  -229.91960238]
 [ 173.1645935  -229.91960238]
 [ 173.1645935  -229.91960238]
 [ 173.1645935  -229.91960238]
 [ 173.1645935  -229.91960238]
 [ 173.1645935  -229.91960238]
 [ 173.1645935  -229.91960238]
 [ 173.1645935  -229.91960238]
 [ 173.1645935  -229.91960238]
 [ 173.1645935  -229.91960238]
 [ 173.1645935  -229.91960238]
 [ 173.1645935  -229.91960238]
 [ 173.1

  1%|▏         | 63/4566 [00:44<2:52:04,  2.29s/it]

[[-278.04634165  -74.42601626]
 [-278.04634165  -74.42601626]
 [-278.04634165  -74.42601626]
 [-278.04634165  -74.42601626]
 [-278.04634165  -74.42601626]
 [-278.04634165  -74.42601626]
 [-278.04634165  -74.42601626]
 [-278.04634165  -74.42601626]
 [-278.04634165  -74.42601626]
 [-278.04634165  -74.42601626]
 [-278.04634165  -74.42601626]
 [-278.56137972  -75.28318356]
 [-277.70363168  -75.79857058]
 [-277.70363168  -75.79857058]
 [-277.70363168  -75.79857058]
 [-277.70363168  -75.79857058]
 [-277.70363168  -75.79857058]
 [-277.70363168  -75.79857058]
 [-277.70363168  -75.79857058]
 [-278.04634165  -74.42601626]
 [-278.04634165  -74.42601626]
 [-278.04634165  -74.42601626]
 [-278.04634165  -74.42601626]
 [-278.04634165  -74.42601626]
 [-278.04634165  -74.42601626]
 [-278.04634165  -74.42601626]
 [-278.04634165  -74.42601626]
 [-278.04634165  -74.42601626]
 [-278.04634165  -74.42601626]
 [-278.04634165  -74.42601626]
 [-278.04634165  -74.42601626]
 [-278.04634165  -74.42601626]
 [-278.0

  1%|▏         | 64/4566 [00:44<2:12:20,  1.76s/it]

[[229.91960238 173.1645935 ]
 [229.91960238 173.1645935 ]
 [229.91960238 173.1645935 ]
 [229.91960238 173.1645935 ]
 [229.91960238 173.1645935 ]
 [229.91960238 173.1645935 ]
 [229.91960238 173.1645935 ]
 [229.91960238 173.1645935 ]
 [229.91960238 173.1645935 ]
 [229.91960238 173.1645935 ]
 [230.07603685 174.15228184]
 [229.08767934 174.30882229]
 [229.08767934 174.30882229]
 [229.08767934 174.30882229]
 [229.08767934 174.30882229]
 [229.08767934 174.30882229]
 [229.08767934 174.30882229]
 [229.08767934 174.30882229]
 [229.91960238 173.1645935 ]
 [229.91960238 173.1645935 ]
 [229.91960238 173.1645935 ]
 [229.91960238 173.1645935 ]
 [229.91960238 173.1645935 ]
 [229.91960238 173.1645935 ]
 [229.91960238 173.1645935 ]
 [229.91960238 173.1645935 ]
 [229.91960238 173.1645935 ]
 [229.91960238 173.1645935 ]
 [229.91960238 173.1645935 ]
 [229.91960238 173.1645935 ]
 [229.91960238 173.1645935 ]
 [229.91960238 173.1645935 ]
 [230.90795989 173.00805304]
 [230.75152542 172.0203647 ]
 [230.75152542

  1%|▏         | 65/4566 [00:44<1:41:06,  1.35s/it]

[[-268.69073036  103.21962709]
 [-268.69073036  103.21962709]
 [-268.69073036  103.21962709]
 [-268.69073036  103.21962709]
 [-268.69073036  103.21962709]
 [-268.69073036  103.21962709]
 [-268.69073036  103.21962709]
 [-268.69073036  103.21962709]
 [-268.69073036  103.21962709]
 [-269.61123522  102.82889596]
 [-269.22023936  101.90776746]
 [-269.22023936  101.90776746]
 [-269.22023936  101.90776746]
 [-269.22023936  101.90776746]
 [-269.22023936  101.90776746]
 [-269.22023936  101.90776746]
 [-269.22023936  101.90776746]
 [-268.69073036  103.21962709]
 [-268.69073036  103.21962709]
 [-268.69073036  103.21962709]
 [-268.69073036  103.21962709]
 [-268.69073036  103.21962709]
 [-268.69073036  103.21962709]
 [-268.69073036  103.21962709]
 [-268.69073036  103.21962709]
 [-268.69073036  103.21962709]
 [-268.69073036  103.21962709]
 [-268.69073036  103.21962709]
 [-268.69073036  103.21962709]
 [-268.69073036  103.21962709]
 [-268.69073036  103.21962709]
 [-269.08172621  104.14075559]
 [-268.1

  1%|▏         | 66/4566 [00:45<1:17:28,  1.03s/it]

[[ 156.70439254 -241.43888121]
 [ 156.70439254 -241.43888121]
 [ 156.70439254 -241.43888121]
 [ 156.70439254 -241.43888121]
 [ 156.70439254 -241.43888121]
 [ 156.70439254 -241.43888121]
 [ 156.70439254 -241.43888121]
 [ 156.70439254 -241.43888121]
 [ 157.67876261 -241.66383226]
 [ 157.90386607 -240.68880205]
 [ 157.90386607 -240.68880205]
 [ 157.90386607 -240.68880205]
 [ 157.90386607 -240.68880205]
 [ 157.90386607 -240.68880205]
 [ 157.90386607 -240.68880205]
 [ 157.90386607 -240.68880205]
 [ 156.70439254 -241.43888121]
 [ 156.70439254 -241.43888121]
 [ 156.70439254 -241.43888121]
 [ 156.70439254 -241.43888121]
 [ 156.70439254 -241.43888121]
 [ 156.70439254 -241.43888121]
 [ 156.70439254 -241.43888121]
 [ 156.70439254 -241.43888121]
 [ 156.70439254 -241.43888121]
 [ 156.70439254 -241.43888121]
 [ 156.70439254 -241.43888121]
 [ 156.70439254 -241.43888121]
 [ 156.70439254 -241.43888121]
 [ 156.70439254 -241.43888121]
 [ 156.47928908 -242.41391141]
 [ 155.50491902 -242.18896036]
 [ 155.5

  1%|▏         | 67/4566 [01:06<8:25:44,  6.74s/it]

[[-258.73669383 -126.11234384]
 [-258.73669383 -126.11234384]
 [-258.73669383 -126.11234384]
 [-258.73669383 -126.11234384]
 [-258.73669383 -126.11234384]
 [-258.73669383 -126.11234384]
 [-258.73669383 -126.11234384]
 [-259.07871397 -127.05203646]
 [-258.1383847  -127.39428832]
 [-258.1383847  -127.39428832]
 [-258.1383847  -127.39428832]
 [-258.1383847  -127.39428832]
 [-258.1383847  -127.39428832]
 [-258.1383847  -127.39428832]
 [-258.1383847  -127.39428832]
 [-258.73669383 -126.11234384]
 [-258.73669383 -126.11234384]
 [-258.73669383 -126.11234384]
 [-258.73669383 -126.11234384]
 [-258.73669383 -126.11234384]
 [-258.73669383 -126.11234384]
 [-258.73669383 -126.11234384]
 [-258.73669383 -126.11234384]
 [-258.73669383 -126.11234384]
 [-258.73669383 -126.11234384]
 [-258.73669383 -126.11234384]
 [-258.73669383 -126.11234384]
 [-258.73669383 -126.11234384]
 [-258.73669383 -126.11234384]
 [-259.67702309 -125.77009197]
 [-259.33500295 -124.83039935]
 [-259.33500295 -124.83039935]
 [-260.2

  1%|▏         | 67/4566 [01:10<1:18:34,  1.05s/it]


KeyboardInterrupt: Interrupted by user